### ISSUE TITLE
add authentication

### ISSUE THREAD

**Issue by azeek21** [azeek21/url_shortener_practice#13]
for usability purposes we already are going to have `weak-uid` and `weak-secret` cookies as soon as user visits website, these cookies will be used to identify user who has not registered yet but wants to use service. With these cookies then we can create and update urls for the user in the database and we will copy all their data to authenticated user as soon as they register or sign up. 

### Tasks 
- [x] Find where to start first :laughing:  [Docs](https://next-auth.js.org/configuration/providers/oauth#override-default-options)
- [x] implement data copy from non user to registered on signup.
    - [x]  implement provider.profile
    - [x] implement [`jwt`](https://next-auth.js.org/configuration/callbacks#jwt-callback) and [`session`](https://next-auth.js.org/configuration/callbacks#session-callback) callbacks to bring user data from database to client side 
- [x] change/ implement logic to support both registered and non registered users. (currently only supports non registered
    - [x] authentication
    - [x] url creation
    - [x] url updates
    - [x] url deleting

**Comment by azeek21** [comment]
[a98a5a2](https://github.com/azeek21/url_shortener_practice/commit/a98a5a2c4352e2139e256530bcdbd99bcd51c43f) implements `githubProvider.profile` correctly and copies `weak-uid` and `weak-secret` to account in nextAuth correctly.

**Comment by azeek21** [comment]
[f85ada7](https://github.com/azeek21/url_shortener_practice/commit/f85ada79864daab611991bb165334f64c79871c9) brings non registered and registered users url CRUD operations. But not tested.

**Comment by azeek21** [comment]
Closing as all tasks are done, auth implemented, but needs small improvement optimizations and bug fixes which are beyond scope of this issue. 

closed by: [c133d70](https://github.com/azeek21/url_shortener_practice/commit/c133d709fa7767a2126c4790e34e25548bf4ba48)
